### ISSUE TITLE
Wire built from sources crashes on log-in (null ptr exception)

### ISSUE THREAD

**Issue by CorvusCorax** [wireapp/wire-android#1288]
## The problem

Wire-android built from sources crashes on user log-in (including auto-login if an account is already configured)
The android client from the appstore works.

**Crash:**
```
E/AndroidRuntime: FATAL EXCEPTION: Thread-180
                  Process: com.waz.zclient.dev, PID: 15561
                  java.lang.NullPointerException: Attempt to invoke interface method 'int com.waz.call.RequestHandler.request(com.waz.call.FlowManager, java.lang.String, java.lang.String, java.lang.String, byte[], long)' on a null object reference
                      at com.waz.call.FlowManager.request(FlowManager.java:365)
```

## Environment

* Wire version that exhibits the issue:
**_branch /release  git commit ID beac0515f44f6866d22671c158c7850b86dd436c_**
* Last Wire version that did not exhibit the issue (if applicable):
**_3.3.374 downloaded from Google Android Store_**
* Android OS version used to run Wire:
**_6.0_**
* Is this a custom firmware or a stock one:
**_Stock_**
* Mobile phone model/manufacturer:
**_Xiomi Redmi Note 4_**
* Mobile network type (EDGE/LTE/Wi-Fi/Offline):
**_Any_**

## Details

Wire compiled as per instructions on the github README.md crashes on attempted login.
This happens both when compiled on the commandline with ./gradlew assembleProdRelease and with android studio 3.0.1, using the ProdRelease target

On most debug targets, such as ProdDebug, compilation fails with:

```
Execution failed for task ':app:transformClassesWithDexForProdDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Too many classes in --main-dex-list, main dex capacity exceeded
```
This seems to be an unrelated issue with the build chain, however compilation succeeds for the DevDebug target with android studio.
The same crash happens right after logging in to the production server with a valid existing account.
The login process internally succeeds to the point that the new device's ID and fingerprint is stored. If the list of devices gets too long, it is possible to delete outdated devices before the client crashes.

Debug Output of the debugger attached to the wire application process can be found in either of the following listings:

## Link to Debug logs
https://pastebin.com/w0nENMHa
https://gist.github.com/CorvusCorax/fc64e0c84b3ceaf9fe6219307083d2fa

Remark: These were generated logging in with a test account, The list of devices was not overflowing so the login immediately triggered the crash.

Remark: Could be the same problem as #1271

**Comment by CorvusCorax** [comment]
2nd remark: the log has another error that occurs before the fatal crash, possibly triggering it:
```
E/Calling: Unable to start avs
           java.lang.UnsatisfiedLinkError: Error looking up function 'wcall_config_update': undefined symbol: wcall_config_update
               at com.sun.jna.Function.<init>(Function.java:245)
               at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:566)
               at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:542)
               at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:528)
               at com.sun.jna.Native.register(Native.java:1770)
               at com.sun.jna.Native.register(Native.java:1643)
               at com.waz.service.call.Calling$.<init>(Calling.scala:35)
               at com.waz.service.call.Calling$.<clinit>(Calling.scala)
               at com.waz.service.call.AvsImpl.<init>(Avs.scala:58)
               at com.waz.service.GlobalModuleImpl.avs$lzycompute(GlobalModule.scala:112)
               at com.waz.service.GlobalModuleImpl.avs(GlobalModule.scala:112)
               at com.waz.service.ZMessaging.avs(ZMessaging.scala:139)
               at com.waz.service.ZMessaging.calling$lzycompute(ZMessaging.scala:211)
               at com.waz.service.ZMessaging.calling(ZMessaging.scala:211)
               at com.waz.service.ZMessaging.gsmService$lzycompute(ZMessaging.scala:229)
               at com.waz.service.ZMessaging.gsmService(ZMessaging.scala:229)
               at com.waz.service.ZMessaging.<init>(ZMessaging.scala:285)
               at com.waz.service.ZMessagingFactory.zmessaging(ZMessaging.scala:73)
               at com.waz.service.AccountManager$$anonfun$19$$anonfun$apply$23$$anonfun$apply$24$$anonfun$apply$27$$anonfun$apply$28$$anonfun$apply$30$$anonfun$apply$31$$anonfun$apply$32.apply(AccountManager.scala:217)
               at com.waz.service.AccountManager$$anonfun$19$$anonfun$apply$23$$anonfun$apply$24$$anonfun$apply$27$$anonfun$apply$28$$anonfun$apply$30$$anonfun$apply$31$$anonfun$apply$32.apply(AccountManager.scala:217)
               at com.waz.utils.LoggedTry$.apply(LoggedTry.scala:28)
               at com.waz.service.AccountManager$$anonfun$19$$anonfun$apply$23$$anonfun$apply$24$$anonfun$apply$27$$anonfun$apply$28$$anonfun$apply$30$$anonfun$apply$31.apply(AccountManager.scala:217)
               at com.waz.service.AccountManager$$anonfun$19$$anonfun$apply$23$$anonfun$apply$24$$anonfun$apply$27$$anonfun$apply$28$$anonfun$apply$30$$anonfun$apply$31.apply(AccountManager.scala:217)
               at scala.Option.orElse(Option.scala:289)
               at com.waz.service.AccountManager$$anonfun$19$$anonfun$apply$23$$anonfun$apply$24$$anonfun$apply$27$$anonfun$apply$28$$anonfun$apply$30.apply(AccountManager.scala:217)
               at com.waz.service.AccountManager$$anonfun$19$$anonfun$apply$23$$anonfun$apply$24$$anonfun$apply$27$$anonfun$apply$28$$anonfun$apply$30.apply(AccountManager.scala:214)
               at scala.Option.map(Option.scala:146)
               at com.waz.utils.events.MapSignal.computeValue(Signal.scala:294)
               at com.waz.utils.events.ProxySignal.onWire(Signal.scala:272)
               at com.waz.utils.events.Observable$class.subscribe(Observable.scala:34)
               at com.waz.utils.events.Signal.subscribe(Signal.scala:90)
               at com.waz.utils.events.FlatMapSignal.onWire(Signal.scala:257)
               at com.waz.utils.events.Observable$class.subscribe(Observable.scala:34)
               at com.waz.utils.events.Signal.subscribe(Signal.scala:90)
               at com.waz.utils.events.FlatMapSignal.onWire(Signal.scala:257)
               at com.waz.utils.events.Observable$class.subscribe(Observable.scala:34)
               at com.waz.utils.events.Signal.subscribe(Signal.scala:90)
               at com.waz.utils.events.FlatMapSignal$$anon$12.changed(Signal.scala:239)
               at com.waz.utils.events.Signal$$anonfun$notifyListeners$2.apply(Signal.scala:110)
               at com.waz.utils.events.Signal$$anonfun$notifyListeners$2.apply(Signal.scala:110)
               at scala.collection.immutable.Set$Set1.foreach(Set.scala:94)
               at com.waz.utils.events.Observable$class.notifyListeners(Observable.scala:46)
               at com.waz.utils.events.Signal.notifyListeners(Signal.scala:110)
               at com.waz.utils.events.Signal.set(Signal.scala:106)
               at com.waz.utils.events.Signal$$anonfun$future$1.applyOrElse(Signal.scala:60)
               at scala.concurrent.Future$$anonfun$onSuccess$1.apply(Future.scala:119)
               at scala.concurrent.Future$$anonfun$onSuccess$1.apply(Future.scala:117)
               at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
               at com.waz.threading.DispatchQueueStats$StatsRunnable.run(DispatchQueueStats.scala:82)
at com.waz.thread

```

**Comment by CorvusCorax** [comment]
# I found the problem as well as a workaround:

## Proprietary app:
The working wireapp from the app store is compiled against a proprietary version of the **wire-audio-and-video-signaling** library (short AVS), as noted in /build.gradle under "customAvsVersion", version **3.6.36**

This in term includes C compilated libavs.so for arm and x86 platforms. This .so exports a symbol (aka callable function) called wcall_config_update(...) which is called by the wire app on login.

This in turn is referenced by the code of the wire-android-sync-engine in file
zmessaging/src/main/scala/com/waz/service/call/Avs.scala line 161:

`override def onConfigRequest(wCall: WCall, error: Int, json: String): Future[Unit] = withAvs(wcall_config_update(wCall, error, json))
`
( wire-android-sync-engine is one of the dependencies pulled in by wire-android as "com.wire.zmessaging-android" )

## Open Source app:

When compiling from (open) source, the same zmessaging library is included, however the precompiled AVS library pulled in by gradle from  http://dl.bintray.com/wire-android/releases/com/wire/avs/ which corresponds to the Open Source code on github in https://github.com/wireapp/wire-audio-video-signaling is two versions behind the proprietary one:
**/build.gradle defines avsVersion = '3.4.100@aar'**

This version, as can be seen in the latest code on github in /src/wcall/wcall.h does not yet define the
wcall_config_update function yet, as its API has apparently evolved since.

As such the app compiled against the open source AVS is not compatible with the used version of zmessaging.

# Workaround:

The proprietary version 3.6.36 of the AVS library can't be found anywhere (except inside the precompiled apk from the appstore - extracting the various .so files from there and injecting it into the selfbuilt apk might be worth a try in order to have the high quality video in a self modified hacked app)
However the gradle aar repository in http://dl.bintray.com/wire-android/releases/com/wire/avs/ has newer precompiled versions of the AVS library than can be found on github.

Although a number of 3.6.x libraries are available, only the last two: 3.6.113 and 3.6.117 define wcall_config_update() in their included library.

Using one of these fixes the crash. Although these precompiled libraries are arguably not open source,  they can be used to compile wireapp-android from branch /release (3.3.x) into an app that does not crash on login.

To use them just change in /build.gradle (https://github.com/wireapp/wire-android/blob/release/build.gradle)
Line 84: avsVersion = '3.4.100@aar'
to
avsVersion = '3.6.117@aar'

and compile. This bundles the app with a late enough libavs.so to not crash with the above error.

**Comment by CorvusCorax** [comment]
Note: with AVS 3.6.117 severe issues during video calls appear, including freezes of the app, freezes of the video in either direction and video being rotated by 90 degree randomly. (Tested with devDebug build)
Audio calls and text messaging on the other hand seem to work fine.
This workaround seems to be OK-ish for debugging of other issues to be able to compile and run the app in the first place, but it doesn't look like a fully functional app can be built easily from sources right now.

**Comment by CorvusCorax** [comment]
Note: copying the production proprietary libavs.so file into an apk compiled either against AVD 3.4.100 or 3.6.117 has interesting and educative effects.
This hack, too works around the original issue (crashes at login). However whenever a call is established (audio or video) some sub process crashes (phone notifies me of a crash but there is nothing showing up in the debug output and the main process keeps running. Oddly enough, there a bi-directional high quality audio (and video) connection does get stablished which remains stable for around 10 seconds after the crash until the connection drops, probably due to a control channel interruption.
AVS consists of more than just the C native compiled libavs.so. There is also java code in the .aar library which ends up a compiled into the final .apk's .dex file. By just switching the .so, this java code which interfaces with the native .so is not updated, so this would only work if the api between native code and bytecode was identical between the two versions. Apparently this is not the case with either 3.4.100 not 3.6.117.

Without source code for a working AVS library available, I see 2 possible ways to fix this. Assuming that the open source repository has working but outdated code, one could either patch (or downgrade) zmessenger to work with the older version, OR add a stub function to the AVS library, so the call to wcall_config_update() succeeds.
I am going to test a zmessenger downgrade next.

**Comment by CorvusCorax** [comment]
Note: Downgrading zmessenger hit another mud-pit
The code change to use wcall_config_update was introduced in git commit 
https://github.com/wireapp/wire-android-sync-engine/commit/6d9f9845
This is between tags 107.0 and 108.0.
I tried downgrading to zmessenger 107 by changine build.gradle, but this already fails during 
dependency resolving since some of the deps of that old zmessenger build are no longer available.

```
Could not find com.localytics.android:library:3.8.0.
           Required by:
               zclient-root:wire-core:unspecified > com.wire:zmessaging-android:107.0.394
```

I could try patching zmessenger and compile from source, but this starts getting way too time consuming to just compile an open source app. 

Can't wire.com provide a precompiled proprietary avs-3.6.36.aar at least in the interim until the open source version is updated to a working state?

Or am I just too blind to find the repository link to it?

**Comment by CorvusCorax** [comment]
Note: The latest zMessenger version that still uses the old Open Source avs API is version 107. Dependency issues can be resolved if git commit f9d776e4bcdc78ac669921b8d38b547336a4d666 is manually applied (cherry picked with conflict fixes, removes localytics dependency)

Unfortunately the rel-3.x branch of wireapp-android references the UiLifeCycle feature provided by wire-android-sync-engine which has only been added post version 112

As such the wireapp-android 3.x will not compile against version 107 of wire-android-sync-engine, and as such cannot compile against 3.4.x versions of AVS.

Sad. I don't know how to fix this. This means the only partial workaround remaining is the precompiled binary release of avs-3.6.117 which has significant bugs and apparently no open sourcecode anywhere. Or is there?

**Comment by CorvusCorax** [comment]
Note: Patching AVS or zmessenger to provide stubs for wcall_config_update is not a viable route either. `wcall_config_update()` is merely the tip of the iceberg, if that is worked around, the app crashes at runtime due to another API change on `wcall_create()`

**Comment by elletlar** [comment]
@CorvusCorax Did you ever solve this?

**Comment by marcoconti83** [comment]
Hi all,
thanks for the detailed reports. Have you tried compiling the project recently? The AVS open source has been updated. 
If you could give it a try again, let us know.

**Comment by marcoconti83** [comment]
Hi all,
I just committed a bump to the AVS version (https://github.com/wireapp/wire-android/commit/8783cd0f8f14217458ab6e3fb0688a39782a6bda), please give this one a try and let us know.

**Comment by hub-ch** [comment]
https://github.com/wireapp/wire-android/issues/1892

**Comment by marcoconti83** [comment]
Hi everyone,
The issue has been fixed here: https://github.com/wireapp/wire-android/issues/1892. Please read the instructions at that link. If this is not fixed for you, please report the issue in the linked discussion and not here.

Thanks for your patience!

**Comment by CorvusCorax** [comment]
Thanks so much for looking into this. I haven't been able to try again yet due to time constraints and not having an android dev environment ready on my computer, but hub-ch's results are very promising. I have little doubts its going to work now, so I'll consider this issue solved.

Thanks a lot for making Open Source great again :-)
