### ISSUE TITLE
no such table: Accounts

### ISSUE THREAD

**Issue by hackerLeiWei** [wireapp/wire-android#2256]
Some exception log occurs when I first  run the application.
```
2019-08-19 12:24:57.522 24153-24218 V/DeferredModeReadTransactionSupport: using deferred mode read transactions
2019-08-19 12:24:57.523 24153-24218 W/Accessing hidden method Landroid/database/sqlite/SQLiteDatabase;->getThreadSession()Landroid/database/sqlite/SQLiteSession; (light greylist, reflection)
2019-08-19 12:24:57.524 24153-24218 W/Accessing hidden method Landroid/database/sqlite/SQLiteSession;->beginTransaction(ILandroid/database/sqlite/SQLiteTransactionListener;ILandroid/os/CancellationSignal;)V (light greylist, linking)
2019-08-19 12:24:57.526 24153-24218 E/SQLiteLog: (1) no such table: Accounts
2019-08-19 12:24:57.527 24153-24153 V/GlobalPreferences: Setting skip_terminating_state (def: false), value: ???
2019-08-19 12:24:57.528 24153-24215 V/GlobalPreferences: GlobalPreferences setValue key:skip_terminating_state value:true
2019-08-19 12:24:57.538 24153-24216 W/AccountsServiceImpl: Failed to migrate databases, aborting operation
    android.database.sqlite.SQLiteException: no such table: Accounts (code 1 SQLITE_ERROR): , while compiling: SELECT * FROM Accounts
        at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
        at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:903)
        at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:514)
        at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
        at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
        at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
        at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:46)
        at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1408)
        at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1255)
        at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1126)
        at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1332)
        at com.waz.utils.wrappers.SQLiteDBWrapper.query(DB.scala:115)
        at com.waz.db.BaseDao.listCursor(Dao.scala:111)
        at com.waz.db.BaseDao.list(Dao.scala:113)
        at com.waz.utils.StorageDao$DbDao.list(CachedStorageImpl.scala:55)
        at com.waz.utils.StorageDao$DbDao.list(CachedStorageImpl.scala:52)
        at com.waz.utils.CachedStorageImpl$$anonfun$list$1.apply(CachedStorageImpl.scala:377)
        at com.waz.utils.CachedStorageImpl$$anonfun$list$1.apply(CachedStorageImpl.scala:377)
        at com.waz.content.Database$$anonfun$read$1$$anonfun$apply$3.apply(Database.scala:43)
        at com.waz.db.package$.inReadTransaction(package.scala:87)
        at com.waz.content.Database$$anonfun$read$1.apply(Database.scala:43)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
        at com.waz.threading.DispatchQueueStats$StatsRunnable.run(DispatchQueueStats.scala:82)
        at com.waz.threading.DispatchQueueStats$StatsRunnable.run(DispatchQueueStats.scala:82)
        at com.waz.threading.LimitedDispatchQueue$Executor$.executeBatch$1(DispatchQueue.scala:102)
        at com.waz.threading.LimitedDispatchQueue$Executor$.run(DispatchQueue.scala:109)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by marcoconti83** [comment]
Hi @hackerLeiWei ,
Thanks for flagging this, is this happening when you install the app from scratch? Are you compiling your own version or are you using our public version?

**Comment by hackerLeiWei** [comment]
@marcoconti83 
I cloned version 3.33.1 of your project and version 139.0 of the engine library. The project did not crash, but there were some abnormal logs.So I want to ask if you have similar questions.

**Comment by marcoconti83** [comment]
Then I believe those logs are from testing if a database exists and is accessible, and they should not cause any problem. If you'd rather remove those logs completely and you feel like contributing, we'd be happy for you to open a PR that addresses the issue!
