### ISSUE TITLE
A conversation can randomly destroy wire and cause OutOfMemory crashes permanently

### ISSUE THREAD

**Issue by UplinkPhobia** [wireapp/wire-android#3518]
**Describe the bug**
On a (usually big) conversation, it sometimes happen that wire stops being able to open the conversation again. Trying causes a long freeze, until wire crashes from what seems to be a memory leak.
This only happens when the conversation is loaded, so it's possible to "bypass" it by quickly tapping on another conversation as soon as wire launches, which will not "load" the cursed conversation. However, trying to open the conversation again will cause the freeze/crash again. Clearing the cache and similar didn't do anything, the only solution I found was to delete data which is not acceptable.
This has happened for quite some time now, with various versions of wire, ROM, etc

**To Reproduce**

1. Have a big conversation
2. Random crash, conversation becomes inaccessible forever
3. ???
4. Don't enjoy

**Expected behavior**
A working conversation

**Smartphone (please complete the following information):**
- Wire version that exhibits the issue: 3.72.1014 and earlier
- Last Wire version that did not exhibit the issue (if applicable): Unknown since the bug appears randomly
- Android OS version used to run Wire: 10
- Is this a custom firmware or a stock one: Custom
- Mobile phone model/manufacturer: Asus Zenfone 
- Mobile network type (EDGE/LTE/Wi-Fi/Offline): Any

**Additional context**

```
FATAL EXCEPTION: main
Process: com.wire, PID: 26826
java.lang.OutOfMemoryError: Failed to allocate a 180352 byte allocation with 138704 free bytes and 135KB until OOM, target footprint 201326592, growth limit 201326592
    at android.view.ViewGroup.addInArray(ViewGroup.java:5258)
    at android.view.ViewGroup.addViewInner(ViewGroup.java:5171)
    at android.view.ViewGroup.addView(ViewGroup.java:4979)
    at android.view.ViewGroup.addView(ViewGroup.java:4919)
    at androidx.recyclerview.widget.RecyclerView$5.addView(RecyclerView.java:856)
    at androidx.recyclerview.widget.ChildHelper.addView(ChildHelper.java:107)
    at androidx.recyclerview.widget.RecyclerView$LayoutManager.addViewInt(RecyclerView.java:8601)
    at androidx.recyclerview.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:8559)
    at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:27547)
    at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
    at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:640)
    at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
    at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3851)
    at androidx.recyclerview.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:1897)
    at androidx.recyclerview.widget.RecyclerView$1.run(RecyclerView.java:414)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1041)
    at android.view.Choreographer.doCallbacks(Choreographer.java:864)
    at android.view.Choreographer.doFrame(Choreographer.java:794)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1026)
    at android.os.Handler.handleCallback(Handler.java:883)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at android.os.Looper.loop(Looper.java:214)
    at android.app.ActivityThread.main(ActivityThread.java:7356)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
```

**Comment by makingthematrix** [comment]
@UplinkPhobia : Interesting! How big was your conversation? Did you also have other big conversations or a big number of it? How many connected users? And could you send me the full logs?

**Comment by UplinkPhobia** [comment]
Just to make things clear, when I talk about big conversation, I mean a conversation with a lot of messages, not a group conversation with a lot of users.
How big is hard to tell, but it's the main conversation I have on my phone and I'd say it takes around 200MB of data. So, big.
Other conversations aren't necessary small, but are still much smaller I think.
As for the logs, I already sent all I had.

I managed to "fix" it, even though I'm not sure what I did. Since I managed to have access to other conversations, I tried using a group conversation with the person's account, but it was old and they couldn't decrypt my messages, so I tried to reset the session, and it might have been what unstuck the main conversation. I can't be sure though, since obviously while I was testing the group conversation, I wasn't observing the main one.

**Comment by makingthematrix** [comment]
@UplinkPhobia : Ok, thanks for the input. It suggests that we have a problem with pagination of messages in a conversation. That part of the code wasn't touched in a while because, well, you're the first person reporting a problem with it in a long time. We're busy with other stuff, but I will make a ticket and see what I can do.
